A test for the user profile. green
With the test data thus prepared, the test itself is fairly
straightforward: we visit the user profile page and check for the page
title and the user’s name, Gravatar, micropost count, and paginated
microposts. The result appears in this commit. Note the use of the
full_title helper from in commit: Defining a full_title helper to test
the page’s title, which we gain access to by including the Application
Helper module into the test.

The micropost count assertion in this commit uses response.body, which
we saw briefly in the Chapter 12: Password reset exercises (Section
12.3.3.1). Despite its name, response.body contains the full HTML source
of the page (and not just the page’s body). This means that if all we
care about is that the number of microposts appears somewhere on the
page, we can look for a match as follows:

```
assert_match @user.microposts.count.to_s, response.body
```

This is a much less specific assertion than assert_select; in
particular, unlike assert_select, using assert_match in this context
doesn’t require us to indicate which HTML tag we’re looking for.

In this commit, introduces the nesting syntax for assert_select:

```
assert_select 'h1>img.gravatar'
```

This checks for an img tag with class gravatar inside a top-level
heading tag (h1).

Because the application code was working, the test suite should be
green:

```
$ rails test
```

Exercises -

1. Comment out the application code needed to change the two ’h1’ lines
in this commit from green to red.

```
def show
  #@user = User.find(params[:id])
  #@microposts = @user.microposts.paginate(page: params[:page])
  #redirect_to root_url and return unless @users.where(activated: true)
# Answer to Ex. 2
end
```

ERROR["test_profile_display", UsersProfileTest, 14.029459323035553]
 test_profile_display#UsersProfileTest (14.03s)
ActionView::Template::Error:         ActionView::Template::Error:
undefined method `name' for nil:NilClass
            app/views/users/show.html.erb:1:in
`_app_views_users_show_html_erb___969897055_99372640'
            test/integration/users_profile_test.rb:11:in `block in
<class:UsersProfileTest>'

E

Error:
UsersProfileTest#test_profile_display:
ActionView::Template::Error: undefined method `name' for nil:NilClass
    app/views/users/show.html.erb:1:in
`_app_views_users_show_html_erb___969897055_99372640'
    test/integration/users_profile_test.rb:11:in `block in
<class:UsersProfileTest>'

bin/rails test test/integration/users_profile_test.rb:10

ERROR["test_valid_signup_information_with_account_activation",
UsersSignupTest, 19.494125858996995]
 test_valid_signup_information_with_account_activation#UsersSignupTest
(19.49s)
ActionView::Template::Error:         ActionView::Template::Error:
undefined method `name' for nil:NilClass
            app/views/users/show.html.erb:1:in
`_app_views_users_show_html_erb___969897055_99372640'
            test/integration/users_signup_test.rb:46:in `block in
<class:UsersSignupTest>'

=E

Error:
UsersSignupTest#test_valid_signup_information_with_account_activation:
ActionView::Template::Error: undefined method `name' for nil:NilClass
    app/views/users/show.html.erb:1:in
`_app_views_users_show_html_erb___969897055_99372640'
    test/integration/users_signup_test.rb:46:in `block in
<class:UsersSignupTest>'

bin/rails test test/integration/users_signup_test.rb:23

ERROR["test_login_with_valid_information_followed_by_logout",
UsersLoginTest, 20.73457764403429]
 test_login_with_valid_information_followed_by_logout#UsersLoginTest
(20.73s)
ActionView::Template::Error:         ActionView::Template::Error:
undefined method `name' for nil:NilClass
            app/views/users/show.html.erb:1:in
`_app_views_users_show_html_erb___969897055_99372640'
            test/integration/users_login_test.rb:25:in `block in
<class:UsersLoginTest>'

=E

Error:
UsersLoginTest#test_login_with_valid_information_followed_by_logout:
ActionView::Template::Error: undefined method `name' for nil:NilClass
    app/views/users/show.html.erb:1:in
`_app_views_users_show_html_erb___969897055_99372640'
    test/integration/users_login_test.rb:25:in `block in
<class:UsersLoginTest>'

bin/rails test test/integration/users_login_test.rb:19

2. Update Listing 13.28 to test that will_paginate appears only once.
Hint: Refer to Table 5.2.
```
assert_match @user.microposts.count.to_s, response.body
assert_select 'div.pagination', count: 1
@user.microposts.paginate(page: 1).each do |micropost|
```