A test for persistent sessions.
This is a problem, of course, because the code in commit: Raising an
exception in an untested branch is broken. Moreover, persistent sessions
are cumbersome to check by hand, so if we ever want to refactor the
current_user method (as we will in Chapter 11) it’s important to test
it.

Because both versions of the log_in_as helper method defined in commit:
Adding a log_in_as helper automatically set session[:user_id] (either
explicitly or by posting to the login path), testing the “remember”
branch of the current_user method is difficult in an integration test.
Luckily, we can bypass this restriction by testing the current_user
method directly in a Sessions helper test, whose file we have to create:

$ touch test/helpers/sessions_helper_test.rb

The test sequence is simple:

1. Define a user variable using the fixtures.
2. Call the remember method to remember the given user.
3. Verify that current_user is equal to the given user.

Because the remember method doesn’t set session[:user_id], this
procedure will test the desired “remember” branch. The result appears
in this commit.

Note that we’ve added a second test, which checks that the current user
is nil if the user’s remember digest doesn’t correspond correctly to
the remember token, thereby testing the authenticated? expression in
the nested if statement:

if user && user.authenticated?(cookies[:remember_token])

Incidentally, in Listing 9.31 we could write

assert_equal current_user, @user

instead, and it would work just the same, but (as mentioned briefly in
Section 5.3.4.1) the conventional order for the arguments to
assert_equal is expected, actual:

assert_equal <expected>, <actual>

which in the case of this commit gives

assert_equal @user, current_user

With the code as in this commit, the test is red as required:

$ rails test test/helpers/sessions_helper_test.rb

Error:
SessionsHelperTest#test_current_user_returns_right_user_when_session_is_nil:
RuntimeError:
    app/helpers/sessions_helper.rb:19:in `current_user'
    test/helpers/sessions_helper_test.rb:11:in `block in
<class:SessionsHelperTest>'

bin/rails test test/helpers/sessions_helper_test.rb:10

ERROR["test_current_user_returns_nil_when_remember_digest_is_wrong",
      SessionsHelperTest, 10.358965233026538]
 test_current_user_returns_nil_when_remember_digest_is_wrong#SessionsHel
                                                        perTest (10.36s)
RuntimeError:         RuntimeError:
            app/helpers/sessions_helper.rb:19:in `current_user'
            test/helpers/sessions_helper_test.rb:17:in `block in <class:
                                                    SessionsHelperTest>'

==================================|
E

Error:
SessionsHelperTest#test_current_user_returns_nil_when_remember_digest_is
                                                                _wrong:
RuntimeError:
    app/helpers/sessions_helper.rb:19:in `current_user'
    test/helpers/sessions_helper_test.rb:17:in `block in <class:Sessions
                                                            HelperTest>'

bin/rails test test/helpers/sessions_helper_test.rb:15