A generalized authenticated? method. red
Recall from the discussion in Section 11.2.1: Mailer templates that the
activation token and email are available as params[:id] and
params[:email], respectively. Following the model of passwords (commit:
Finding and authenticating a user) and remember tokens (commit: Updating
current_user for persistent sessions), we plan to find and authenticate
the user with code something like this:

```
user = User.find_by(email: params[:email])
if user && user.authenticated?(:activation, params[:id])
```

(As we’ll see in a moment, there will be one extra boolean in the
expression above. See if you can guess what it will be.)

The above code uses the authenticated? method to test if the account
activation digest matches the given token, but at present this won’t
work because that method is specialized to the remember token (commit:
Adding an authenticated? method to the User model):

```

def authenticated?(remember_token)
  return false if remember_digest.nil?
  BCrypt::Password.new(remember_digest).is_password?(remember_token)
end
```

Here remember_digest is an attribute on the User model, and inside the
model we can rewrite it as follows:

```
self.remember_digest
```
Somehow, we want to be able to make this variable, so we can call

```
self.activation_digest
```
instead by passing in the appropriate parameter to the authenticated?
method.

The solution involves our first example of metaprogramming, which is
essentially a program that writes a program. (Metaprogramming is one of
Ruby’s strongest suits, and many of the “magic” features of Rails are
due to its use of Ruby metaprogramming.) The key in this case is the
powerful send method, which lets us call a method with a name of our
choice by “sending a message” to a given object. For example, in this
console session we use send on a native Ruby object to find the length
of an array:

```
$ rails console
>> a = [1, 2, 3]
>> a.length
=> 3
>> a.send(:length)
=> 3
>> a.send("length")
=> 3
```

Here we see that passing the symbol :length or string "length" to send
is equivalent to calling the length method on the given object. As a
second example, we’ll access the activation_digest attribute of the
first user in the database:

```
>> user = User.first
>> user.activation_digest
=> "$2a$10$4e6TFzEJAVNyjLv8Q5u22ensMt28qEkx0roaZvtRcp6UZKRM6N9Ae"
>> user.send(:activation_digest)
=> "$2a$10$4e6TFzEJAVNyjLv8Q5u22ensMt28qEkx0roaZvtRcp6UZKRM6N9Ae"
>> user.send("activation_digest")
=> "$2a$10$4e6TFzEJAVNyjLv8Q5u22ensMt28qEkx0roaZvtRcp6UZKRM6N9Ae"
>> attribute = :activation
>> user.send("#{attribute}_digest")
=> "$2a$10$4e6TFzEJAVNyjLv8Q5u22ensMt28qEkx0roaZvtRcp6UZKRM6N9Ae"
```

Note in the last example that we’ve defined an attribute variable equal
to the symbol :activation and used string interpolation to build up the
proper argument to send. This would work also with the string
’activation’, but using a symbol is more conventional, and in either
case

```
"#{attribute}_digest"
```

becomes

```
"activation_digest"
```
once the string is interpolated. (We saw how symbols are interpolated as
strings in commit: Adding a flash message to user signup)

Based on this discussion of send, we can rewrite the current
authenticated? method as follows:

```
def authenticated?(remember_token)
  digest = self.send("remember_digest")
  return false if digest.nil?
  BCrypt::Password.new(digest).is_password?(remember_token)
end
```

With this template in place, we can generalize the method by adding a
function argument with the name of the digest, and then use string
interpolation as above:

```
def authenticated?(attribute, token)
  digest = self.send("#{attribute}_digest")
  return false if digest.nil?
  BCrypt::Password.new(digest).is_password?(token)
end
```

(Here we have renamed the second argument token to emphasize that it’s
now generic.) Because we’re inside the user model, we can also omit
self, yielding the most idiomatically correct version:

```
def authenticated?(attribute, token)
  digest = send("#{attribute}_digest")
  return false if digest.nil?
  BCrypt::Password.new(digest).is_password?(token)
end
```

We can now reproduce the previous behavior of authenticated? by invoking
it like this:

```
user.authenticated?(:remember, remember_token)
```

Applying this discussion to the User model yields the generalized
authenticated? method shown in this commit.

Now test this commit with test suite and it should be RED:
$ rails test

ERROR["test_current_user_returns_nil_when_remember_digest_is_wrong",
SessionsHelperTes
                                                    t,
47.31257667200407]
test_current_user_returns_nil_when_remember_digest_is_wrong#SessionsHelperTest
(47.31
                                         s)
ArgumentError:         ArgumentError: wrong number of arguments (1 for
2)
            app/models/user.rb:43:in `authenticated?'
            app/helpers/sessions_helper.rb:25:in `current_user'
            test/helpers/sessions_helper_test.rb:17:in `block in
<class:SessionsHelper
                                                        Test>'

==E

Error:
SessionsHelperTest#test_current_user_returns_nil_when_remember_digest_is_wrong:
ArgumentError: wrong number of arguments (1 for 2)
    app/models/user.rb:43:in `authenticated?'
    app/helpers/sessions_helper.rb:25:in `current_user'
    test/helpers/sessions_helper_test.rb:17:in `block in
<class:SessionsHelperTest>'

bin/rails test test/helpers/sessions_helper_test.rb:15

ERROR["test_current_user_returns_right_user_when_session_is_nil",
SessionsHelperTest,

47.33359638298862]
test_current_user_returns_right_user_when_session_is_nil#SessionsHelperTest
(47.33s)
ArgumentError:         ArgumentError: wrong number of arguments (1 for
2)
            app/models/user.rb:43:in `authenticated?'
            app/helpers/sessions_helper.rb:25:in `current_user'
            test/helpers/sessions_helper_test.rb:11:in `block in
<class:SessionsHelper
                                                        Test>'

==E

Error:
SessionsHelperTest#test_current_user_returns_right_user_when_session_is_nil:
ArgumentError: wrong number of arguments (1 for 2)
    app/models/user.rb:43:in `authenticated?'
    app/helpers/sessions_helper.rb:25:in `current_user'
    test/helpers/sessions_helper_test.rb:11:in `block in
<class:SessionsHelperTest>'

bin/rails test test/helpers/sessions_helper_test.rb:10

ERROR["test_authenticated?_should_return_false_for_a_user_with_nil_digest",
UserTest, 51.20457386499038]
test_authenticated?_should_return_false_for_a_user_with_nil_digest#UserTest
(51.20s)
ArgumentError:         ArgumentError: wrong number of arguments (1 for
2)
            app/models/user.rb:43:in `authenticated?'
            test/models/user_test.rb:77:in `block in <class:UserTest>'

===E

Error:
UserTest#test_authenticated?_should_return_false_for_a_user_with_nil_digest:
ArgumentError: wrong number of arguments (1 for 2)
    app/models/user.rb:43:in `authenticated?'
    test/models/user_test.rb:77:in `block in <class:UserTest>'

bin/rails test test/models/user_test.rb:76

.===..===.=.==..===..====..===.=.==.==..==.===|
.
Finished in 51.74211s
43 tests, 181 assertions, 0 failures, 3 errors, 0 skips

Finished in 51.982186s, 0.8272 runs/s, 3.4820 assertions/s.
43 runs, 181 assertions, 0 failures, 3 errors, 0 skips